name: Python 3.6
on: 
  #schedule:
  #  - cron: "* * * * *"
  push:
    branches:
      - "master"
      - "feature/*"
      - "!feature/featC"
    #tags:
     # - "v1.*"
     #paths:
     #  - "**.js"
  pull_request:
    types: [closed, assigned, opened, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        make install
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test

